# Generated by Django 3.0.2 on 2020-02-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='assunto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agenda.Assunto'),
            preserve_default=False,
        ),
    ]
