# Generated by Django 3.0.2 on 2020-02-09 22:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_auto_20200205_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Evento',
        ),
    ]
