# Generated by Django 3.0.2 on 2020-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20200209_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='descricao',
            field=models.CharField(max_length=120, unique=True, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição'),
        ),
    ]
