# Generated by Django 3.0.2 on 2020-02-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='categoria_telefone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comum.Categoria_Telefone'),
            preserve_default=False,
        ),
    ]
