# Generated by Django 3.0.2 on 2020-02-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_telefone_categoria_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_telefone',
            options={'ordering': ['descricao'], 'verbose_name': 'Categoria de Telefone', 'verbose_name_plural': 'Categorias de Telefones'},
        ),
        migrations.AlterField(
            model_name='categoria_telefone',
            name='descricao',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
