# Generated by Django 3.0.2 on 2020-02-12 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=2000, null=True)),
                ('foto', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=120)),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('assunto_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.AssuntoSolicitacao')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Bairro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-dt_inclusao'],
            },
        ),
    ]
