# Generated by Django 3.0.2 on 2020-02-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='assunto_solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.AssuntoSolicitacao', verbose_name='Assunto'),
        ),
    ]
