# Generated by Django 3.0.2 on 2020-02-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('solicitacao', '0002_auto_20200211_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, unique=True, verbose_name='Descrição')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterModelOptions(
            name='assuntosolicitacao',
            options={'ordering': ['descricao'], 'verbose_name': 'Assunto', 'verbose_name_plural': 'Assuntos'},
        ),
        migrations.AlterField(
            model_name='assuntosolicitacao',
            name='descricao',
            field=models.CharField(max_length=120, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Bairro'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='numero',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='solicitacao.Situacao'),
        ),
    ]
