# Generated by Django 3.0.2 on 2020-02-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_auto_20200212_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='situacao',
        ),
        migrations.DeleteModel(
            name='Situacao',
        ),
    ]
