# Generated by Django 3.0.2 on 2020-02-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_auto_20200212_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuntosolicitacao',
            name='user',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='solicitacao.Situacao'),
        ),
    ]
