# Generated by Django 3.0.2 on 2020-02-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('A', 'Ambos'), ('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('experiencia', models.BooleanField(default=False)),
                ('dt_fim', models.DateTimeField(verbose_name='Dt. Retirada')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemprego.Cargo')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bemprego.Escolaridade')),
            ],
            options={
                'ordering': ['cargo'],
            },
        ),
    ]
