# Generated by Django 3.0.2 on 2020-02-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemprego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolaridade',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='descricao',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
