# Generated by Django 2.1.2 on 2020-02-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemprego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolaridade',
            options={'ordering': ['id']},
        ),
    ]
