# Generated by Django 2.1.2 on 2020-02-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemprego', '0002_auto_20200212_0002'),
        ('bemprego', '0002_auto_20200209_2114'),
    ]

    operations = [
    ]
