# Generated by Django 3.0 on 2020-02-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcivil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico_alerta',
            options={'ordering': ['-dt_inclusao'], 'verbose_name': 'Histórico de Alerta', 'verbose_name_plural': 'Históricos de Alerta'},
        ),
        migrations.AlterModelOptions(
            name='ponto_apoio',
            options={'ordering': ['nome'], 'verbose_name': 'Ponto de Apoio', 'verbose_name_plural': 'Pontos de Apoio'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'ordering': ['nome'], 'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AddField(
            model_name='ponto_apoio',
            name='capacidade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ponto_apoio',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
