# Generated by Django 3.0 on 2020-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcivil', '0002_auto_20200202_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirigente',
            name='celular',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsavel',
            name='celular',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ponto_apoio',
            name='dirigente',
        ),
        migrations.AddField(
            model_name='ponto_apoio',
            name='dirigente',
            field=models.ManyToManyField(blank=True, to='dcivil.Dirigente'),
        ),
        migrations.RemoveField(
            model_name='ponto_apoio',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='ponto_apoio',
            name='responsavel',
            field=models.ManyToManyField(blank=True, to='dcivil.Responsavel'),
        ),
    ]
