# Generated by Django 3.0.2 on 2020-02-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcivil', '0005_historico_alerta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_apoio',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dirigente',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_apoio',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
