# Generated by Django 3.0.2 on 2020-02-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcivil', '0006_auto_20200204_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='estagio',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
